### PR TITLE
rewrite the definitions of groups in symmetry.jl

### PR DESCRIPTION
**Pull request by kalmarek**
you can check the correctness of group definitions using
```julia
include(joinpath(pathof(GroupsCore), "..", "..", "test", "conformance_test.jl"))
let G = KleinGroup()
    test_Group_interface(G)
    test_GroupElement_interface(rand(G, 2)...)
    nothing
end
let G = KleinPermGroup()
    test_Group_interface(G)
    test_GroupElement_interface(rand(G, 2)...)
    nothing
end
let G = CyclicGroup(12)
    test_Group_interface(G)
    test_GroupElement_interface(rand(G, 2)...)
    nothing
end
let G = lattice1group(5)
    test_Group_interface(G)
    test_GroupElement_interface(rand(G, 2)...)
    nothing
end
```

### CODE REVIEW

**Comment by blegat** [comment]
Wow, that was fast. Was it incorrect before ?

**Comment by kalmarek** [comment]
yeah, I found them a bit earlier ;) took me ~2h to rewrite;

I'm not sure it was incorrect, it didn't pass the tests because of missing methods.

**Comment by kalmarek** [comment]
following interfaces is nice ;) everything is green here, locally ;)

**Comment by blegat** [comment]
So does that mean that SymbolicWedderburn was not running enough checks on the group ?

**Comment by blegat** [comment]
Maybe https://discourse.julialang.org/t/symmetry-sos-optimization-compatibility-issues/98057/6 has a similar issue, the group is not valid but with more checks an error would be thrown

**Comment by kalmarek** [comment]
SymbolicWedderburn doesn't do any checks per se (it does now for the group action);
Here I just made sure that our groups comply to the group interface. User should do that on his own, I suppose?

**Comment by blegat** [comment]
I think it's best if we do it by default and then the user can disable it with options. The power users will set the option to disable but the new user that does not know the option, he will also most probably have errors in the group ^^

**Comment by kalmarek** [comment]
ok, I'll think about it

**Pull request merged**
